name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read
      pages: read

    container:
      image: ghcr.io/miti-7/miti-blog-hugo@sha256:66c030b7dddb937dd67340bc4ec04d983518f1aaa3cb432eabe3aa984689b9e7
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: false
          fetch-depth: 0

      - name: Configure Git
        run: git config --global --add safe.directory '*'

      - name: Checkout theme
        run: git submodule update --init --recursive themes/hugo-theme-stack

      - name: Checkout latest articles
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: MitI-7/articles
          path: articles
          token: ${{ secrets.ARTICLES_TOKEN }}
          fetch-depth: 1

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
